const list = [
  { flag: 'flags-normal/flag-of-Afghanistan.png', name: 'Afghanistan' },
  { flag: 'flags-normal/flag-of-Albania.png', name: 'Albania' },
  { flag: 'flags-normal/flag-of-Algeria.png', name: 'Algeria' },
  { flag: 'flags-normal/flag-of-Andorra.png', name: 'Andorra' },
  { flag: 'flags-normal/flag-of-Angola.png', name: 'Angola' },
  { flag: 'flags-normal/flag-of-Antigua.png', name: 'Antigua and Barbuda' },
  { flag: 'flags-normal/flag-of-Argentina.png', name: 'Argentina' },
  { flag: 'flags-normal/flag-of-Armenia.png', name: 'Armenia' },
  { flag: 'flags-normal/flag-of-Australia.png', name: 'Australia' },
  { flag: 'flags-normal/flag-of-Austria.png', name: 'Austria' },
  { flag: 'flags-normal/flag-of-Azerbaijan.png', name: 'Azerbaijan' },
  { flag: 'flags-normal/flag-of-Bahamas.png', name: 'Bahamas' },
  { flag: 'flags-normal/flag-of-Bahrain.png', name: 'Bahrain' },
  { flag: 'flags-normal/flag-of-Bangladesh.png', name: 'Bangladesh' },
  { flag: 'flags-normal/flag-of-Barbados.png', name: 'Barbados' },
  { flag: 'flags-normal/flag-of-Belarus.png', name: 'Belarus' },
  { flag: 'flags-normal/flag-of-Belgium.png', name: 'Belgium' },
  { flag: 'flags-normal/flag-of-Belize.png', name: 'Belize' },
  { flag: 'flags-normal/flag-of-Benin.png', name: 'Benin' },
  { flag: 'flags-normal/flag-of-Bhutan.png', name: 'Bhutan' },
  { flag: 'flags-normal/flag-of-Bolivia.png', name: 'Bolivia' },
  { flag: 'flags-normal/flag-of-Bosnia-Herzegovina.png', name: 'Bosnia and Herzegovina' },
  { flag: 'flags-normal/flag-of-Botswana.png', name: 'Botswana' },
  { flag: 'flags-normal/flag-of-Brazil.png', name: 'Brazil' },
  { flag: 'flags-normal/flag-of-Brunei.png', name: 'Brunei' },
  { flag: 'flags-normal/flag-of-Bulgaria.png', name: 'Bulgaria' },
  { flag: 'flags-normal/flag-of-Burkina-Faso.png', name: 'Burkina Faso' },
  { flag: 'flags-normal/flag-of-Burundi.png', name: 'Burundi' },
  { flag: 'flags-normal/flag-of-Cabo-Verde.png', name: 'Cabo Verde' },
  { flag: 'flags-normal/flag-of-Cambodia.png', name: 'Cambodia' },
  { flag: 'flags-normal/flag-of-Cameroon.png', name: 'Cameroon' },
  { flag: 'flags-normal/flag-of-Canada.png', name: 'Canada' },
  { flag: 'flags-normal/flag-of-Central-African-Republic.png', name: 'Central African Republic' },
  { flag: 'flags-normal/flag-of-Chad.png', name: 'Chad' },
  { flag: 'flags-normal/flag-of-Chile.png', name: 'Chile' },
  { flag: 'flags-normal/flag-of-China.png', name: 'China' },
  { flag: 'flags-normal/flag-of-Colombia.png', name: 'Colombia' },
  { flag: 'flags-normal/flag-of-Comoros.png', name: 'Comoros' },
  { flag: 'flags-normal/flag-of-Congo-Democratic-Republic-of.png', name: 'Congo, Democratic Republic of the' },
  { flag: 'flags-normal/flag-of-Congo.png', name: 'Congo, Republic of the' },
  { flag: 'flags-normal/flag-of-Costa-Rica.png', name: 'Costa Rica' },
  { flag: 'flags-normal/flag-of-Cote-d-Ivoire.png', name: "Cote d'Ivoire" },
  { flag: 'flags-normal/flag-of-Croatia.png', name: 'Croatia' },
  { flag: 'flags-normal/flag-of-Cuba.png', name: 'Cuba' },
  { flag: 'flags-normal/flag-of-Cyprus.png', name: 'Cyprus' },
  { flag: 'flags-normal/flag-of-Czech-Republic.png', name: 'Czechia' },
  { flag: 'flags-normal/flag-of-Denmark.png', name: 'Denmark' },
  { flag: 'flags-normal/flag-of-Djibouti.png', name: 'Djibouti' },
  { flag: 'flags-normal/flag-of-Dominica.png', name: 'Dominica' },
  { flag: 'flags-normal/flag-of-Dominican-Republic.png', name: 'Dominican Republic' },
  { flag: 'flags-normal/flag-of-Ecuador.png', name: 'Ecuador' },
  { flag: 'flags-normal/flag-of-Egypt.png', name: 'Egypt' },
  { flag: 'flags-normal/flag-of-El-Salvador.png', name: 'El Salvador' },
  { flag: 'flags-normal/flag-of-Equatorial-Guinea.png', name: 'Equatorial Guinea' },
  { flag: 'flags-normal/flag-of-Eritrea.png', name: 'Eritrea' },
  { flag: 'flags-normal/flag-of-Estonia.png', name: 'Estonia' },
  { flag: 'flags-normal/flag-of-Eswatini.png', name: 'Eswatini (formerly Swaziland)' },
  { flag: 'flags-normal/flag-of-Ethiopia.png', name: 'Ethiopia' },
  { flag: 'flags-normal/flag-of-Fiji.png', name: 'Fiji' },
  { flag: 'flags-normal/flag-of-Finland.png', name: 'Finland' },
  { flag: 'flags-normal/flag-of-France.png', name: 'France' },
  { flag: 'flags-normal/flag-of-Gabon.png', name: 'Gabon' },
  { flag: 'flags-normal/flag-of-Gambia.png', name: 'Gambia' },
  { flag: 'flags-normal/flag-of-Georgia.png', name: 'Georgia' },
  { flag: 'flags-normal/flag-of-Germany.png', name: 'Germany' },
  { flag: 'flags-normal/flag-of-Ghana.png', name: 'Ghana' },
  { flag: 'flags-normal/flag-of-Greece.png', name: 'Greece' },
  { flag: 'flags-normal/flag-of-Grenada.png', name: 'Grenada' },
  { flag: 'flags-normal/flag-of-Guatemala.png', name: 'Guatemala' },
  { flag: 'flags-normal/flag-of-Guinea.png', name: 'Guinea' },
  { flag: 'flags-normal/flag-of-Guinea-Bissau.png', name: 'Guinea-Bissau' },
  { flag: 'flags-normal/flag-of-Guyana.png', name: 'Guyana' },
  { flag: 'flags-normal/flag-of-Haiti.png', name: 'Haiti' },
  { flag: 'flags-normal/flag-of-Honduras.png', name: 'Honduras' },
  { flag: 'flags-normal/flag-of-Hungary.png', name: 'Hungary' },
  { flag: 'flags-normal/flag-of-Iceland.png', name: 'Iceland' },
  { flag: 'flags-normal/flag-of-India.png', name: 'India' },
  { flag: 'flags-normal/flag-of-Indonesia.png', name: 'Indonesia' },
  { flag: 'flags-normal/flag-of-Iran.png', name: 'Iran' },
  { flag: 'flags-normal/flag-of-Iraq.png', name: 'Iraq' },
  { flag: 'flags-normal/flag-of-Ireland.png', name: 'Ireland' },
  { flag: 'flags-normal/flag-of-Israel.png', name: 'Israel' },
  { flag: 'flags-normal/flag-of-Italy.png', name: 'Italy' },
  { flag: 'flags-normal/flag-of-Jamaica.png', name: 'Jamaica' },
  { flag: 'flags-normal/flag-of-Japan.png', name: 'Japan' },
  { flag: 'flags-normal/flag-of-Jordan.png', name: 'Jordan' },
  { flag: 'flags-normal/flag-of-Kazakhstan.png', name: 'Kazakhstan' },
  { flag: 'flags-normal/flag-of-Kenya.png', name: 'Kenya' },
  { flag: 'flags-normal/flag-of-Kiribati.png', name: 'Kiribati' },
  { flag: 'flags-normal/flag-of-Kosovo.png', name: 'Kosovo' },
  { flag: 'flags-normal/flag-of-Kuwait.png', name: 'Kuwait' },
  { flag: 'flags-normal/flag-of-Kyrgyzstan.png', name: 'Kyrgyzstan' },
  { flag: 'flags-normal/flag-of-Laos.png', name: 'Laos' },
  { flag: 'flags-normal/flag-of-Latvia.png', name: 'Latvia' },
  { flag: 'flags-normal/flag-of-Lebanon.png', name: 'Lebanon' },
  { flag: 'flags-normal/flag-of-Lesotho.png', name: 'Lesotho' },
  { flag: 'flags-normal/flag-of-Liberia.png', name: 'Liberia' },
  { flag: 'flags-normal/flag-of-Libya.png', name: 'Libya' },
  { flag: 'flags-normal/flag-of-Liechtenstein.png', name: 'Liechtenstein' },
  { flag: 'flags-normal/flag-of-Lithuania.png', name: 'Lithuania' },
  { flag: 'flags-normal/flag-of-Luxembourg.png', name: 'Luxembourg' },
  { flag: 'flags-normal/flag-of-Madagascar.png', name: 'Madagascar' },
  { flag: 'flags-normal/flag-of-Malawi.png', name: 'Malawi' },
  { flag: 'flags-normal/flag-of-Malaysia.png', name: 'Malaysia' },
  { flag: 'flags-normal/flag-of-Maldives.png', name: 'Maldives' },
  { flag: 'flags-normal/flag-of-Mali.png', name: 'Mali' },
  { flag: 'flags-normal/flag-of-Malta.png', name: 'Malta' },
  { flag: 'flags-normal/flag-of-Marshall-Islands.png', name: 'Marshall Islands' },
  { flag: 'flags-normal/flag-of-Mauritania.png', name: 'Mauritania' },
  { flag: 'flags-normal/flag-of-Mauritius.png', name: 'Mauritius' },
  { flag: 'flags-normal/flag-of-Mexico.png', name: 'Mexico' },
  { flag: 'flags-normal/flag-of-Micronesia.png', name: 'Micronesia' },
  { flag: 'flags-normal/flag-of-Moldova.png', name: 'Moldova' },
  { flag: 'flags-normal/flag-of-Monaco.png', name: 'Monaco' },
  { flag: 'flags-normal/flag-of-Mongolia.png', name: 'Mongolia' },
  { flag: 'flags-normal/flag-of-Montenegro.png', name: 'Montenegro' },
  { flag: 'flags-normal/flag-of-Morocco.png', name: 'Morocco' },
  { flag: 'flags-normal/flag-of-Mozambique.png', name: 'Mozambique' },
  { flag: 'flags-normal/flag-of-Myanmar.png', name: 'Myanmar (formerly Burma)' },
  { flag: 'flags-normal/flag-of-Namibia.png', name: 'Namibia' },
  { flag: 'flags-normal/flag-of-Nauru.png', name: 'Nauru' },
  { flag: 'flags-normal/flag-of-Nepal.png', name: 'Nepal' },
  { flag: 'flags-normal/flag-of-Netherlands.png', name: 'Netherlands' },
  { flag: 'flags-normal/flag-of-New-Zealand.png', name: 'New Zealand' },
  { flag: 'flags-normal/flag-of-Nicaragua.png', name: 'Nicaragua' },
  { flag: 'flags-normal/flag-of-Niger.png', name: 'Niger' },
  { flag: 'flags-normal/flag-of-Nigeria.png', name: 'Nigeria' },
  { flag: 'flags-normal/flag-of-Korea-North.png', name: 'North Korea' },
  { flag: 'flags-normal/flag-of-North-Macedonia.png', name: 'North Macedonia (formerly Macedonia)' },
  { flag: 'flags-normal/flag-of-Norway.png', name: 'Norway' },
  { flag: 'flags-normal/flag-of-Oman.png', name: 'Oman' },
  { flag: 'flags-normal/flag-of-Pakistan.png', name: 'Pakistan' },
  { flag: 'flags-normal/flag-of-Palau.png', name: 'Palau' },
  { flag: 'flags-normal/flag-of-Palestine.png', name: 'Palestine' },
  { flag: 'flags-normal/flag-of-Panama.png', name: 'Panama' },
  { flag: 'flags-normal/flag-of-Papua-New-Guinea.png', name: 'Papua New Guinea' },
  { flag: 'flags-normal/flag-of-Paraguay.png', name: 'Paraguay' },
  { flag: 'flags-normal/flag-of-Peru.png', name: 'Peru' },
  { flag: 'flags-normal/flag-of-Philippines.png', name: 'Philippines' },
  { flag: 'flags-normal/flag-of-Poland.png', name: 'Poland' },
  { flag: 'flags-normal/flag-of-Portugal.png', name: 'Portugal' },
  { flag: 'flags-normal/flag-of-Qatar.png', name: 'Qatar' },
  { flag: 'flags-normal/flag-of-Romania.png', name: 'Romania' },
  { flag: 'flags-normal/flag-of-Russia.png', name: 'Russia' },
  { flag: 'flags-normal/flag-of-Rwanda.png', name: 'Rwanda' },
  { flag: 'flags-normal/flag-of-St-Kitts-Nevis.png', name: 'Saint Kitts and Nevis' },
  { flag: 'flags-normal/flag-of-St-Lucia.png', name: 'Saint Lucia' },
  { flag: 'flags-normal/flag-of-St-Vincent-the-Grenadines.png', name: 'Saint Vincent and the Grenadines' },
  { flag: 'flags-normal/flag-of-Samoa.png', name: 'Samoa' },
  { flag: 'flags-normal/flag-of-San-Marino.png', name: 'San Marino' },
  { flag: 'flags-normal/flag-of-Sao-Tome-and-Principe.png', name: 'Sao Tome and Principe' },
  { flag: 'flags-normal/flag-of-Saudi-Arabia.png', name: 'Saudi Arabia' },
  { flag: 'flags-normal/flag-of-Senegal.png', name: 'Senegal' },
  { flag: 'flags-normal/flag-of-Serbia.png', name: 'Serbia' },
  { flag: 'flags-normal/flag-of-Seychelles.png', name: 'Seychelles' },
  { flag: 'flags-normal/flag-of-Sierra-Leone.png', name: 'Sierra Leone' },
  { flag: 'flags-normal/flag-of-Singapore.png', name: 'Singapore' },
  { flag: 'flags-normal/flag-of-Slovakia.png', name: 'Slovakia' },
  { flag: 'flags-normal/flag-of-Slovenia.png', name: 'Slovenia' },
  { flag: 'flags-normal/flag-of-Solomon-Islands.png', name: 'Solomon Islands' },
  { flag: 'flags-normal/flag-of-Somalia.png', name: 'Somalia' },
  { flag: 'flags-normal/flag-of-South-Africa.png', name: 'South Africa' },
  { flag: 'flags-normal/flag-of-Korea-South.png', name: 'South Korea' },
  { flag: 'flags-normal/flag-of-South-Sudan.png', name: 'South Sudan' },
  { flag: 'flags-normal/flag-of-Spain.png', name: 'Spain' },
  { flag: 'flags-normal/flag-of-Sri-Lanka.png', name: 'Sri Lanka' },
  { flag: 'flags-normal/flag-of-Sudan.png', name: 'Sudan' },
  { flag: 'flags-normal/flag-of-Suriname.png', name: 'Suriname' },
  { flag: 'flags-normal/flag-of-Sweden.png', name: 'Sweden' },
  { flag: 'flags-normal/flag-of-Switzerland.png', name: 'Switzerland' },
  { flag: 'flags-normal/flag-of-Syria.png', name: 'Syria' },
  { flag: 'flags-normal/flag-of-Taiwan.png', name: 'Taiwan' },
  { flag: 'flags-normal/flag-of-Tajikistan.png', name: 'Tajikistan' },
  { flag: 'flags-normal/flag-of-Tanzania.png', name: 'Tanzania' },
  { flag: 'flags-normal/flag-of-Thailand.png', name: 'Thailand' },
  { flag: 'flags-normal/flag-of-Timor-Leste.png', name: 'Timor-Leste' },
  { flag: 'flags-normal/flag-of-Togo.png', name: 'Togo' },
  { flag: 'flags-normal/flag-of-Tonga.png', name: 'Tonga' },
  { flag: 'flags-normal/flag-of-Trinidad-and-Tobago.png', name: 'Trinidad and Tobago' },
  { flag: 'flags-normal/flag-of-Tunisia.png', name: 'Tunisia' },
  { flag: 'flags-normal/flag-of-Turkey.png', name: 'Turkey' },
  { flag: 'flags-normal/flag-of-Turkmenistan.png', name: 'Turkmenistan' },
  { flag: 'flags-normal/flag-of-Tuvalu.png', name: 'Tuvalu' },
  { flag: 'flags-normal/flag-of-Uganda.png', name: 'Uganda' },
  { flag: 'flags-normal/flag-of-Ukraine.png', name: 'Ukraine' },
  { flag: 'flags-normal/flag-of-United-Arab-Emirates.png', name: 'United Arab Emirates' },
  { flag: 'flags-normal/flag-of-United-Kingdom.png', name: 'United Kingdom' },
  { flag: 'flags-normal/flag-of-United-States-of-America.png', name: 'United States of America' },
  { flag: 'flags-normal/flag-of-Uruguay.png', name: 'Uruguay' },
  { flag: 'flags-normal/flag-of-Uzbekistan.png', name: 'Uzbekistan' },
  { flag: 'flags-normal/flag-of-Vanuatu.png', name: 'Vanuatu' },
  { flag: 'flags-normal/flag-of-Vatican-City.png', name: 'Vatican City (Holy See)' },
  { flag: 'flags-normal/flag-of-Venezuela.png', name: 'Venezuela' },
  { flag: 'flags-normal/flag-of-Vietnam.png', name: 'Vietnam' },
  { flag: 'flags-normal/flag-of-Yemen.png', name: 'Yemen' },
  { flag: 'flags-normal/flag-of-Zambia.png', name: 'Zambia' },
  { flag: 'flags-normal/flag-of-Zimbabwe.png', name: 'Zimbabwe' },
];

export default list;
