const listLanguage = {
  vi: 'VI',
  en: 'EN',
};

const HomePageLanguage = {
  vi: {
    title: 'Ví đa chức năng tiên phong trong lĩnh vực Game Blockchain và lưu trữ tài sản số',
    desc1: 'An toàn',
    desc2: 'Bảo mật cao',
    desc3: 'Thuận tiện',
    sub_title1: 'KHÁM PHÁ TẠI SAO CHÚNG TÔI KHÁC BIỆT',
    sub_desc1_1:
      'King Wallet là ví đa chức năng tiên phong trong lĩnh vực Game Blockchain và lưu trữ tài sản số. Người dùng có thể gửi, nhận, hoán đổi hoặc tham gia Staking tiền điện tử của mình thuận tiện và dễ dàng!',
    sub_desc1_2:
      'King Wallet đáp ứng tất cả nhu cầu của cộng đồng người dùng Game token cũng như các loại tiền điện tử khác.',
    slide_title1: 'Giao dịch nhanh chóng',
    slide_desc1:
      'Được xây dựng bằng công nghệ blockchain giúp tăng tốc độ giao dịch lên hàng trăm giao dịch mỗi giây. Hiệu suất cao này sẽ cho phép người dùng gửi và rút tiền một cách nhanh chóng, mất ít thời gian chờ đợi, thuận tiện và an toàn hơn.',
    slide_title2: 'Ví lưu trữ đa tiền tệ',
    slide_desc2:
      'King Wallet được xây dựng để trở thành một ví blockchain có thể mở rộng để hỗ trợ các mã game token và nhiều loại tiền điện tử khác nhau trên thị trường. Tài sản của bạn có thể được truy cập một cách an toàn vào bất cứ lúc nào và bất cứ đâu.',
    slide_title3: 'Bảo mật và giao dịch an toàn',
    slide_desc3:
      'King Wallet được trang bị một cơ chế bảo mật nhiều tầng để đảm bảo rằng tất cả các tài sản và giao dịch được thực hiện đều an toàn và ổn định. Người dùng có thể sử dụng sinh trắc học, mã pin, mật khẩu  và Google 2FA để nâng cao bảo mật tài khoản.',
    slide_title4: 'Cảnh báo thời gian thực',
    slide_desc4:
      'Người dùng sẽ nhận được thông báo theo thời gian thực mỗi khi tài khoản có sự thay đổi về số dư, thay đổi bảo mật hoặc tin tức quan trọng. Hãy bật tính năng này để cho phép thiết bị của bạn luôn nhận được tin tức quan trọng một cách kịp thời.',
    sub_title2: 'TÍNH NĂNG NỔI BẬT',
    sub_desc2_1:
      'Chúng tôi cung cấp cho bạn một dịch vụ ví ưu việt thế hệ tiếp theo phù hợp với nhu cầu của mọi người dùng Game cũng như cộng đồng người dùng tiền điện tử. Với King Wallet, người dùng còn được tận hưởng nhiều tính năng nổi bật như Staking, Token swap hay cổng Game Hub chuyên biệt cho Game thủ và Nhà phát triển.',
    list_title1: 'HỖ TRỢ GAME TOKEN, TRC-20 VÀ ERC-20 TOKEN',
    list_desc1:
      'King Wallet sẽ hỗ trợ lưu trữ KDG, các loại Game token trên nền tảng ERC-20 và TRC-20 Token. Các loại mã token khác sẽ được bổ sung trong tương lai để cho phép người dùng đa dạng hóa danh mục lưu trữ và đầu tư của mình.',
    list_title2: 'GAME HUB',
    list_desc2:
      'Cổng chuyên biệt về Game ứng cộng công nghệ blockchain và giải pháp thanh toán do Kingdom Game xây dựng và phát triển. GAME HUB cung cấp cho người dùng mảng Game giải trí đa dạng, cung cấp cho các Nhà phát triển một giải pháp chuyên biệt về thanh toán và phát hành sản phẩm. ',
    list_title3: 'THU NHẬP THỤ ĐỘNG',
    list_desc3:
      'Ví đầu tiền hỗ trợ Staking Game token và nhiều loại tiền kỹ thuật số khác để nhận lợi tức. King Wallet cho phép người dùng gia tăng giá trị và số lượng với các loại tiền điện tử mà người dùng đang nắm giữ một cách thuận tiện và an toàn.',
    list_title4: 'HOÁN ĐỔI DỄ DÀNG',
    list_desc4:
      'King Wallet cung cấp cho bạn phương tiện nhanh chóng và dễ dàng để hoán đổi Game token, Tron token cũng như Ethereum token. Các tính năng mới sẽ được cập nhật liên tục và bổ sung thêm nhiều mã token khác trong tương lai để phục vụ nhu cầu người dùng.',
  },
  en: {
    title: 'Multi-function wallet pioneers in the field of Blockchain Game and Digital Asset Storage',
    desc1: 'Safety',
    desc2: 'High security',
    desc3: 'Facilitation',
    sub_title1: 'DISCOVER WHY WE ARE UNIQUE',
    sub_desc1_1:
      'King Wallet is a pioneering multi-function wallet in the field of Blockchain Game and Digital Asset Storage. Users can send, receive, swap or participate in their Crypto Staking conveniently and easily!',
    sub_desc1_2: 'King Wallet meets all the needs of the Game Token community as well as other cryptocurrencies.',
    slide_title1: 'Fast transaction',
    slide_desc1:
      'Built with blockchain technology that speeds up transactions to hundreds of transactions per second. This high performance will allow users to deposit and withdraw money quickly, with less waiting time, and more convenient and secure.',
    slide_title2: 'Multi-currency storage wallets',
    slide_desc2:
      'King Wallet is built to be a scalable blockchain wallet to support game tokens and various cryptocurrencies in the market. Your property can be securely accessed anytime and anywhere.',
    slide_title3: 'Security and secure transactions',
    slide_desc3:
      'King Wallet is equipped with a multi-tier security mechanism to ensure that all assets and transactions made are safe and stable. Users can use biometrics, PIN code, password and Google 2FA to enhance account security.',
    slide_title4: 'Real-time alerts',
    slide_desc4:
      'Users receive real-time notifications when an account has a balance change, security change or important news. Turn this feature on to allow your device to always receive important news in a timely manner.',
    sub_title2: 'PROMINENT FEATURES',
    sub_desc2_1:
      'We provide you with a premium next generation wallet service tailored to the needs of all Game users and the Crypto community. With King Wallet, users also enjoy many outstanding features such as Staking, Token Swap or a specialized Game Hub portal for gamers and developers.',
    list_title1: 'SUPPORT TOKEN GAME, TRC-20 AND ERC-20 TOKEN',
    list_desc1:
      'King Wallet will support KDG storage, ERC-20 and TRC-20 Token Game. More tokens will be added in the future to allow users to diversify their storage portfolio and investment.',
    list_title2: 'GAME HUB',
    list_desc2:
      'A specialized portal for the Game of Blockchain technology and payment solutions built and developed by Kingdom Game. GAME HUB provides users with a diversified type of Entertainment, providing Developers a specialized solution for payment and product distribution.',
    list_title3: 'PASSIVE INCOME',
    list_desc3:
      'The first wallet supports Staking Game Tokens and many other digital currencies to receive profits. King Wallet allows users to increase the value and quantity with the cryptocurrencies they are holding in a convenient and secure way.',
    list_title4: 'EASY TO SWAP',
    list_desc4:
      'King Wallet provides you with a quick and easy way of swapping Game Tokens, Tron Tokens as well as Ethereum Tokens. New features will be updated continuously and added more tokens in the future to serve the needs of users.',
  },
};

const WalletPageLanguage = {
  vi: {
    market: 'Giá thị trường',
    balance_information: 'thông tin số dư',
    history: 'LỊCH SỬ GIAO DỊCH',
    date: 'Thời gian',
    volume: 'Số lượng',
    type: 'Kiểu',
    deposit: 'Nạp',
    withdrawal: 'Rút',
    swap: 'Swap',
    stake: 'Stake',
    receive_money_stake: 'Nhận tiền staking',
    receive_profit_stake: 'Nhận lãi staking',
    nodata: 'Không có dữ liệu',
    copied: 'Đã copy',
    withdraw_error_100: 'Vui lòng thiết lập 2FA trước',
    withdraw_error_101: '2FA không đúng',
    withdraw_error_102: 'Vui lòng xác minh danh tính trước',
    withdraw_error_103: 'Số lượng rút tối thiểu không đủ',
    withdraw_error_104: 'Số dư không đủ',
    withdraw_success: 'Rút tiền thành công',
    swap_error_101: 'Số lượng swap chưa đạt mức tối thiểu',
    swap_error_102: 'Số lượng swap vượt mức tối đa',
    swap_error_103: 'Bạn đã swap vượt quá số lần trong ngày',
    swap_success: 'Bạn đã swap thành công',
    address: 'Địa chỉ',
    amount: 'Số lượng',
    google_2FA: 'Mã Google 2FA',
    swap_with: 'Swap với',
    receive: 'Nhận được',
    available: 'Khả dụng:',
    locked: 'Đã khoá:',
  },
  en: {
    market: 'MARKET',
    balance_information: 'BALANCE INFORMATION',
    history: 'HISTORY',
    date: 'Date',
    volume: 'Volume',
    type: 'Type',
    deposit: 'Deposit',
    withdrawal: 'Withdrawal',
    swap: 'Swap',
    stake: 'Stake',
    receive_money_stake: 'Receive stake',
    receive_profit_stake: 'Receive profit from stake',
    nodata: 'No data',
    copied: 'Copied',
    withdraw_error_100: 'Please active 2FA',
    withdraw_error_101: 'Incorrect 2FA',
    withdraw_error_102: 'Please complete KYC',
    withdraw_error_103: 'Transaction minimum not enough',
    withdraw_error_104: 'Not enough balance',
    withdraw_success: 'Withdraw Successfully',
    swap_error_101: 'Swap quantity has not reached minimum',
    swap_error_102: 'Swap quantity has exceeded maximum',
    swap_error_103: 'The number of swap times is exceeded',
    swap_success: 'Swap successfully',
    address: 'Address',
    amount: 'Amount',
    google_2FA: 'Google 2FA',
    swap_with: 'Swap with',
    receive: 'Receive',
    available: 'Available:',
    locked: 'Locked:',
  },
};

const StakingHomePageLanguage = {
  vi: {
    desc1: 'mô hình kinh tế chia sẻ trong thế giới số',
    desc2:
      'Với hệ sinh thái Staking của Kingdom Game, người dùng không chỉ nắm giữ Token đơn thuần mà còn được tận hưởng thu nhập thụ động. King Wallet cung cấp dịch vụ Staking cho các loại Game Token và nhiều đồng tiền kỹ thuật số khác để hạn chế sự mất giá của Token từ lạm phát và tăng lợi tức cho người dùng.',
    block1: 'Lợi tức cao lên tới <br/> 48%/năm',
    block2: 'Hỗ trợ Game Token, ERC-20 <br/> và TRC-20 Token',
    block3: 'Stake KDG nhận thêm <br/> Token Game khác miễn phí',
    total_stake: 'Tổng Stake (~USDT)',
    profit: 'Lợi Nhuận (~USDT)',
    balance: 'Số dư',
    operation: 'Hoạt động',
    join: 'Tham gia',
    history: 'Lịch sử',
  },
  en: {
    desc1: 'SHARING ECONOMICS IN THE DIGITAL WORLD',
    desc2:
      'With the Kingdom Game ecosystem, users not only hold tokens but also enjoy additional passive income. King Wallet provides Staking program for Game Tokens and many other digital currencies to limit the devaluation of Token from inflation and increase profit for users.',
    block1: 'High income up to <br/> 48%/year',
    block2: 'Support Game Token, ERC-20 <br/> and TRC-20 Token',
    block3: 'Stake KDG gets another <br/> Token Game khác for free',
    total_stake: 'Total Stake (~USDT)',
    profit: 'Profit (~USDT)',
    balance: 'Balance',
    operation: 'Operation',
    join: 'Join',
    history: 'History',
  },
};

const StakingJoinPageLanguage = {
  vi: {
    success: 'Staking thành công',
    back: 'Trở về',
    profit_rate: 'Tỷ lệ lợi nhuận tham chiếu lên tới',
    stack_package: 'Các Gói Stake',
    choose_stack_package: 'Chọn một trong số các gói stake dưới đây:',
    days: 'Ngày',
    investment_amount: 'Số Lượng Đầu Tư',
    enter_investment_amount: 'Nhập số lượng bạn muốn đầu tư',
    available_balance: 'Số dư khả dụng:',
    enter_stake_amount: 'Nhập số lượng đầu tư:',
    minimum: 'Tối thiểu',
    maximum: 'Tối đa',
    daily_interest: 'Lợi nhuận ngày',
    total_principal_and_interest: 'Tổng gốc & lãi',
    confirm_information: 'Xác Nhận Thông Tin',
    please_read: 'Vui lòng đọc kỹ quy tắc trước khi tham gia',
    desc1: 'Lãi suất được trả lúc 8:00 hàng ngày (Tối thiểu 24 tiếng cho lần nhận lãi đầu tiên).',
    desc2:
      'Kết thúc thời hạn stake, người dùng có thể rút khoản gốc đã stake trong vòng 05 ngày bằng cách nhấn xác nhận kết thúc stake. Khoản stake không được rút sẽ được tự động gia hạn.',
    agreement:
      'Tôi đã đọc và hiểu rõ <a href="terms-of-service/1" target="_blank" className="link">cảnh báo rủi ro</a> trước khi tham gia',
    join_now: 'Tham gia ngay',
  },
  en: {
    success: 'Staking success',
    back: 'Back',
    profit_rate: 'Expected annual rate of return up to',
    stack_package: 'Lookup Options',
    choose_stack_package: 'Choose one of the Staking packages below:',
    days: 'Days',
    investment_amount: 'Investment Amount',
    enter_investment_amount: 'Enter the amount you want to invest',
    available_balance: 'Available balance:',
    enter_stake_amount: 'Enter amount to stake:',
    minimum: 'Minimum',
    maximum: 'Maximum',
    daily_interest: 'Daily interest',
    total_principal_and_interest: 'Total principal & interest',
    confirm_information: 'Confirm information',
    please_read: 'Please read the rules carefully before joining',
    desc1: 'Interest is paid at 8:00 every day (Min 24 hours for the first interest payment).',
    desc2:
      'At the end of the Stake period, users can withdraw the Stake original within 05 days by pressing the button to confirm. Stakes that are not withdrawn will be automatically renewed.',
    agreement:
      'I have read and understood the risk warning before participating <a href="terms-of-service/1" target="_blank" className="link">the risk warning</a> before participating',
    join_now: 'Join now',
  },
};

const StakingHistoryPageLanguage = {
  vi: {
    renew_success: 'Gia hạn thành công',
    end_success: 'Kết thúc staking thành công',
    progressing: 'Đang nhận lãi',
    finished: 'Kết thúc',
    waiting_for_unlock: 'Waiting for unlock',
    renewal: 'Gia hạn staking',
    back: 'Trở về',
    my_staking_record: 'LỊCH SỬ STAKING',
    create_date: 'Ngày tạo staking',
    start_date: 'Thời gian bắt đầu trả lãi',
    end_date: 'Thời gian kết thúc trả lãi',
    unlock_date: 'Thời gian mở khóa',
    staking_quantity: 'Số tiền staking',
    profit_receive: 'Lợi nhuận đã nhận',
    status: 'Trạng thái',
  },
  en: {
    renew_success: 'Renew success',
    end_success: 'End Success',
    progressing: 'Progressing',
    finished: 'Finished',
    waiting_for_unlock: 'Chờ mở khóa',
    renewal: 'Renewal',
    back: 'Back',
    my_staking_record: 'MY STAKING RECORD',
    create_date: 'Create date',
    start_date: 'Start date',
    end_date: 'End date',
    unlock_date: 'Unlock date',
    staking_quantity: 'Staking quantity',
    profit_receive: 'Profit receive',
    status: 'Status',
  },
};

const AccountPageLanguage = {
  vi: {
    account: 'TÀI KHOẢN',
    personal_info: 'Thông tin cá nhân',
    view_and_update_info: 'Xem và cập nhật thông tin',
    security_settings: 'Bảo mật tài khoản',
    security_utilities: 'Các tiện ích bảo mật',
    referral: 'Giới thiệu',
    introduce_new_member: 'Giới thiệu thành viên mới',
    get_reward_points: 'Tích điểm thưởng',
    account_verification: 'Xác thực tài khoản',
    kyc_notyet: 'chưa KYC',
    kyc_success: 'KYC Thành công',
    kyc_pending: 'KYC Đang duyệt',
    kyc_rejected: 'KYC Bị từ chối',
    update_info_success: 'Cập nhật thông tin thành công',
    surname: 'Họ',
    last_name: 'Tên',
    phone_number: 'Số điện thoại',
    gender: 'Giới tính',
    male: 'Nam',
    female: 'Nữ',
    date_of_birth: 'Ngày sinh',
    invalid_date: 'Ngày sinh phải đúng định dạng DD/MM/YYYY',
    address: 'Địa chỉ',
    update: 'Cập nhật',
    copied: 'Đã copy',
    change_password_success: 'Cập nhật mật khẩu thành công',
    change_password_error_100: 'Mật khẩu cũ không chính xác',
    verify_2fa_success: 'Cài đặt 2FA thành công',
    verify_2fa_error_100: 'Cài đặt 2FA không thành công',
    disable_2fa_success: 'Hủy 2FA thành công',
    disable_2fa_error_100: 'Mã 2FA không chính xác',
    disable_2fa_error_101: 'Sai mật khẩu',
    setting_2FA: 'CÀI ĐẶT 2FA',
    scan_here: 'Scan tại đây',
    click_to_copy: 'Click để sao chép mã',
    code_2FA: 'Nhập mã 2FA trong app của bạn',
    confirm_2FA: 'Xác nhận 2FA',
    disable_2FA: 'HỦY 2FA',
    enter_password: 'Nhập mật khẩu',
    confirm_disable_2FA: 'Xác nhận hủy 2FA',
    change_password: 'THAY ĐỔI MẬT KHẨU',
    old_password: 'Mật khẩu cũ',
    enter_old_password: 'Nhập mật khẩu cũ',
    new_password: 'Mật khẩu mới',
    error_password: 'Password phải ít nhất 8 ký tự cả chữ và số',
    enter_new_password: 'Nhập mật khẩu mới',
    confirm_new_password: 'Xác nhận mật khẩu mới',
    password_not_match: 'Password không khớp',
    rewarded: 'Phần thưởng của tôi',
    kyc_success_number: 'Số người KYC thành công',
    rewarded_list: 'Danh sách Phần thưởng của tôi',
    date: 'Thời gian',
    from: 'Nhận từ',
    status: 'Tình trạng',
    nodata: 'Không có dữ liệu',
    current_reward_points: 'Điểm thưởng hiện tại:',
    referral_link: 'Liên kết giới thiệu:',
    referral_code: 'Mã giới thiệu:',
    rules: 'Quy luật',
    rules_1:
      '1. Bất kỳ ai mời một người đăng ký tài khoản thành công, sau đó thực hiện xác minh danh tính (KYC) thành công sẽ nhận được 5 KDG reward.',
    rules_2: '2. Không giới hạn lời mời, càng mời nhiều bạn, càng nhận được nhiều KDG reward.',
    rules_3: '3. Bất kỳ ai người dùng cùng 1 thiết bị, cùng một số điện thoại sẽ được xem như một người dùng.',
    rules_4: '4. Bất kỳ ai đăng nhập bất thường hoặc theo các hình thức gian lận sẽ không nhận được phần thưởng',
  },
  en: {
    account: 'ACCOUNT',
    personal_info: 'Account',
    view_and_update_info: 'View and update information',
    security_settings: 'Security Settings',
    security_utilities: 'Security utilities',
    referral: 'Referral',
    introduce_new_member: 'Introduce new members',
    get_reward_points: 'Get reward points',
    account_verification: 'Account verification',
    kyc_notyet: 'Not yet',
    kyc_success: 'Confirmed',
    kyc_pending: 'Pending',
    kyc_rejected: 'Rejected',
    update_info_success: 'Update information successfully',
    surname: 'Surname',
    last_name: 'Last Name',
    phone_number: 'Phone Number',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    date_of_birth: 'Date of Birth',
    invalid_date: 'Date is invalid',
    address: 'Address',
    update: 'Update',
    copied: 'Copied',
    change_password_success: 'Change password success',
    change_password_error_100: 'Wrong old password',
    verify_2fa_success: '2FA activate successfully',
    verify_2fa_error_100: '2FA activate fail',
    disable_2fa_success: 'Disable 2FA successfully',
    disable_2fa_error_100: 'Wrong 2FA',
    disable_2fa_error_101: 'Wrong password',
    setting_2FA: 'SETTING 2FA',
    scan_here: 'Scan here',
    click_to_copy: 'Click to copy code',
    code_2FA: 'Enter 2FA code in your app',
    confirm_2FA: 'Confirm 2FA',
    disable_2FA: 'DISABLE 2FA',
    enter_password: 'Enter password',
    confirm_disable_2FA: 'Confirm disable 2FA',
    change_password: 'CHANGE PASSWORD',
    old_password: 'Old password',
    enter_old_password: 'Enter your old password',
    new_password: 'New password',
    error_password: 'At least 8 digits, include word and number',
    enter_new_password: 'Enter your new password',
    confirm_new_password: 'Confirm new password',
    password_not_match: 'Password not match',
    rewarded: 'Rewarded',
    kyc_success_number: 'Number of successful KYC people',
    rewarded_list: 'Rewarded list',
    date: 'Date',
    from: 'From',
    status: 'Status',
    nodata: 'No data',
    current_reward_points: 'Current reward points:',
    referral_link: 'Referral link:',
    referral_code: 'Referral code:',
    rules: 'Rules',
    rules_1: '1. Anyone who successfully invites someone who completes KYC verification, will receive 5 KDG reward.',
    rules_2: '2. No limit invitations, the more invitation, the more KDG rewards you get.',
    rules_3: '3. Anyone using the same device, same phone number will be seen as one user.',
    rules_4: '4. Anyone who signs in with cheating ways or abnormal ways will not receive any rewards.',
  },
};

const Tab3PageLanguage = {
  vi: {
    ID: 'Chứng minh nhân dân/ Bằng lái xe',
    passport: 'Hộ chiếu',
    file_size_exceeds_2MB: 'Kích thước tệp vượt quá 2MB',
    img_upload_error: 'Tải hình lên không thành công, vui lòng thử lại',
    resUpdate_success: 'Gửi KYC thành công, bạn vui lòng chờ xét duyệt',
    resUpdate_error_100: 'Số chứng minh/passport đã được sử dụng cho tài khoản khác',
    resUpdate_error: 'Gửi KYC không thành công, vui lòng thử lại',
    document_type: 'Loại giấy tờ',
    nation: 'Quốc gia',
    name: 'Tên',
    exactly_name: 'Tên chính xác trên chứng minh / hộ chiếu',
    so: 'Số ',
    desc_1: 'Vui lòng sử dụng định dạng JPG, JPEG, PNG. Kích thước tệp tối đa = 2MB',
    desc_2: 'Để đảm bảo quá trình xác minh được thuận tiện, vui lòng không che hoặc làm nhòe ảnh.',
    passport_image: '1. Ảnh chụp hộ chiếu',
    front_ID: '1. Mặt trước CMND/Bằng lái xe',
    back_ID: '2. Mặt sau CMND/ Bằng lái xe',
    click_upload_front: 'Nhấn vào đây để tải lên ảnh mặt trước',
    click_upload_back: 'Nhấn vào đây để tải lên ảnh mặt sau',
    click_upload: 'Nhấn vào đây để tải lên',
    text_1:
      '. Ảnh có mặt bạn chụp chung với CMND/Bằng lái xe/Hộ chiếu và một tờ giấy ghi tay chữ "KINGDOM GAME 4.0", ngày tháng năm hiện tại và chữ ký của bạn.(Chính diện)',
    text_2:
      '. Ảnh có mặt bạn chụp chung với CMND/Bằng lái xe/Hộ chiếu và một tờ giấy ghi tay chữ "KINGDOM GAME 4.0", ngày tháng năm hiện tại và chữ ký của bạn. (Mặt phía bên trái)',
    text_3:
      '. Ảnh có mặt bạn chụp chung với CMND/Bằng lái xe/Hộ chiếu và một tờ giấy ghi tay chữ "KINGDOM GAME 4.0", ngày tháng năm hiện tại và chữ ký của bạn. (Mặt phía bên phải)',
    text_4:
      '. Ảnh có mặt bạn chụp chung với CMND/Bằng lái xe/Hộ chiếu và một tờ giấy ghi tay chữ "KINGDOM GAME 4.0", ngày tháng năm hiện tại và chữ ký của bạn. (Mặt ngước lên)',
    confirm_upload: 'Tôi xác nhận các thông tin trên là đúng sự thật',
    xac_nhan: 'XÁC NHẬN',
  },
  en: {
    ID: "Identity Card / Driver's License",
    passport: 'Passport',
    file_size_exceeds_2MB: 'File size exceeds 2MB',
    img_upload_error: 'Upload images error, please try again',
    resUpdate_success: 'Send KYC info to admin success. Please wait!',
    resUpdate_error_100: 'Your ID is used for another account',
    resUpdate_error: 'Send KYC fail, please try again!',
    document_type: 'Document type',
    nation: 'Nation',
    name: 'Name',
    exactly_name: 'Name exactly on your ID / Passport',
    so: '',
    desc_1: 'Please use the format JPG., JPEG., PNG. Maximum file size = 2MB',
    desc_2: 'To ensure the verification process most quickly, please do not hide or blur the image',
    passport_image: '1. Passport image',
    front_ID: "1. ID card / Driver's license front image",
    back_ID: "2. ID card / Driver's license back image",
    click_upload_front: 'Click here to upload front',
    click_upload_back: 'Click here to upload back',
    click_upload: 'Click here to upload',
    text_1: `. Image with your face taken with your ID / Driver's License / Passport and a piece of paper which there is a hand written sentence "KINGDOM GAME 4.0", current date and your signature in that.(Keep straight)`,
    text_2: `. Image with your face taken with your ID / Driver's License / Passport and a piece of paper which there is a hand written sentence "KINGDOM GAME 4.0", current date and your signature in that.(Turn left)`,
    text_3: `. Image with your face taken with your ID / Driver's License / Passport and a piece of paper which there is a hand written sentence "KINGDOM GAME 4.0", current date and your signature in that.(Turn right)`,
    text_4: `. Image with your face taken with your ID / Driver's License / Passport and a piece of paper which there is a hand written sentence "KINGDOM GAME 4.0", current date and your signature in that.(Turn up)`,
    confirm_upload: 'I certify that the above information is true',
    xac_nhan: 'CONFIRM',
  },
};

export const initialState = {
  language: 'en',
  listLanguage,
  HomePageLanguage,
  WalletPageLanguage,
  StakingHomePageLanguage,
  StakingJoinPageLanguage,
  StakingHistoryPageLanguage,
  AccountPageLanguage,
  Tab3PageLanguage,
};

export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';

export const reducer = (state, action) => {
  switch (action.type) {
    case CHANGE_LANGUAGE:
      return {
        ...state,
        language: action.payload,
      };
    default:
      return state;
  }
};
